USE database biblioteca_pessoaL_1S2026;
CREATE TABLE usuario(
id_usuario INT AUTO_INCREMENT PRIMARY KEY;
nome VARCHAR(255)
email VARCHAR (128)
);

ALTER TABLE usuario
MODIFY COLUMN nome VARCHAR(255) NOT NULL,
MODIFY COLUMN email VARCHAR(128) NOT NULL;
DESCRIBE usuario;

ALTER TABLE usuario
ADD COLUMN senha VARCHAR(255) NOT NULL,
ADD COLUMN data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
